#!/bin/sh
#Lucas Manker
#Homework 2
#2/7/20

now="$(date +'%A, %b %d, %Y: %H%M')"

if [[ $# -lt 1 ]]; then
   echo "usage: modify filename [filename ....]"
fi

for arg in "$@"
do
   if [[ -d $arg ]]; then
      echo "$arg, is a directory."
   elif [[ -x $arg ]]; then
      echo "$arg, cannot edit executables."
   elif [[ -f $arg ]]; then
      if [[ "$(file "$arg")" =~ ': ASCII text'$ ]]; then 
         echo 'Modified on: '"$now" >> $arg
         echo 'Modified by: '"$USER" >> $arg
         ed -s $arg <<-HERE
         1m2
         w
HERE
         ed -s $arg <<-HERE > /dev/null 2>&1
         ,s/Gradez/Grades
         w
HERE
      else
         echo "$arg, filetype not supported"
      fi
   else
      echo "$arg, filetype not supported"
   fi
done
